[workspace]

members = [
    "pcode-rs",         # Rust PCode Bindings
    "ire",              # Rust implementation of angr
    "iir",              # The IRE IR
    "ire-disassembler", # Disassembler for IRE
]
